---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guacamole.fullname" . }}-frontend
  labels: {{- include "guacamole.labels.frontend" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}