{{- if .Values.frontend.ingress.enabled }}
---
{{- if semverCompare ">=1.19.0" $.Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "guacamole.fullname" . }}-frontend
  {{- if .Values.frontend.ingress.annotations }}
  annotations: {{- .Values.frontend.ingress.annotations | toYaml | nindent 4 }}
  labels: {{- include "guacamole.labels.frontend" . | nindent 4 }}
spec:
  {{- if .Values.frontend.ingress.class }}
  {{- if semverCompare ">=1.19.0" $.Capabilities.KubeVersion.Version }}
  ingressClassName: {{ .Values.frontend.ingress.class }}
  {{- else }}
  {{- fail "Please set the kubernetes.io/ingress.class annotation instead" }}
  {{- end }}
  {{- end }}
  {{- if .Values.frontend.ingress.hosts }}
  rules:
    {{- range $i, $host := .Values.frontend.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          {{- range $j, $path := $host.paths }}
          - path: {{ $path }}
          {{- if semverCompare ">=1.19.0" $.Capabilities.KubeVersion.Version }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "guacamole.fullname" $ }}-frontend
                port:
                  name: http
          {{- else }}
            backend:
              serviceName: {{ include "guacamole.fullname" $ }}-frontend
              servicePort: http
          {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- range $i, $tls := .Values.frontend.ingress.tls }}
    - secretName: {{ $tls.secretName }}
      hosts:
        {{- range $j, $host := $tls.hosts }}
        - {{ $host }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
