{{- if .Values.frontend.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "guacamole.fullname" . }}-frontend
  labels: {{- include "guacamole.labels.frontend" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels: {{- include "guacamole.selectorLabels.frontend" . | nindent 6 }}
{{- end }}
