{{- if not .Values.database.postgres.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-frontend
  labels: {{- include "guacamole.labels.frontend" . | nindent 4 }}
data:
  # Database credentials
  POSTGRES_PASSWORD: {{ .Values.database.postgres.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.postgres.user | b64enc | quote }}
{{- end }}
