---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-frontend
  labels: {{- include "guacamole.labels.frontend" . | nindent 4 }}
spec:
  selector: {{- include "guacamole.selectorLabels.frontend" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
