apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cachet
  name: cachet
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8000
  selector:
    io.kompose.service: cachet
status:
  loadBalancer: {}
