apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cachet
  name: cachet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cachet
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cachet
    spec:
      containers:
      - env:
        - name: APP_DEBUG
          value: "false"
        - name: APP_ENV
          value: production
        - name: APP_KEY
          value: "null"
        - name: APP_LOG
          value: errorlog
        - name: DB_DATABASE
          value: postgres
        - name: DB_DRIVER
          value: pgsql
        - name: DB_HOST
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_PREFIX
          value: chq_
        - name: DB_USERNAME
          value: postgres
        - name: DEBUG
          value: "false"
        image: cachet
        imagePullPolicy: ""
        name: cachet
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
