apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ template "cachet.name" . }}
    chart: {{ template "cachet.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "cachet.fullname" . }}
data:
  APP_KEY: {{ .Values.appKey | b64enc | quote }}

  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}

  MAIL_USERNAME: {{ .Values.email.userName | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.email.password | b64enc | quote }}
