apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachet.fullname" . }}
  labels:
{{ include "cachet.labels" . | indent 4 }}
data:
{{ range $key, $value := .Values.env.private }}
  {{ $key }}: {{ $value | b64enc }}
{{- end -}}
