apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "cachet.name" . }}
    chart: {{ template "cachet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name:  {{ template "cachet.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
  selector:
    app: {{ template "cachet.name" . }}
    release: {{ .Release.Name }}
