apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: "{{ .Values.replicaCount }}"
  strategy: {}
  template:
    spec:
      containers:
      - env:
        - name: GUACD_HOSTNAME
          value: "{{ .Values.guacd.HostName }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.mysql.MYSQL_DATABASE }}"
        - name: MYSQL_HOSTNAME
          value: "{{ .Values.mysql.HostName }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.mysql.MYSQL_PASSWORD }}"
        - name: MYSQL_USER
          value: "{{ .Values.mysql.MYSQL_USER }}"
        image: "{{ .Values.guacamole.image.repository }}"
        imagePullPolicy: "{{ .Values.guacamole.image.pullPolicy }}"
        name: guacamole
        ports:
        - containerPort: 8080
        resources: {}
      hostname: "{{ .Values.guacamole.HostName }}"
      restartPolicy: "{{ .Values.guacamole.image.restartPolicy }}"
      serviceAccountName: "{{ template "guacamole.serviceAccountName" . }}"
      volumes: null
status: {}
