apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\bin\kompose.exe convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: guacamole
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guacamole
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\bin\kompose.exe convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: guacamole
    spec:
      containers:
      - env:
        - name: GUACD_HOSTNAME
          value: guacd
        - name: MYSQL_DATABASE
          value: guacadb
        - name: MYSQL_HOSTNAME
          value: mysql
        - name: MYSQL_PASSWORD
        - name: MYSQL_USER
          value: guacamole_user
        image: guacamole/guacamole
        imagePullPolicy: ""
        name: guacamole
        ports:
        - containerPort: 8080
        resources: {}
      hostname: guacamole
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
