apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\bin\kompose.exe convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: guacd
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guacd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\bin\kompose.exe convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: guacd
    spec:
      containers:
      - image: guacamole/guacd
        imagePullPolicy: ""
        name: guacd
        resources: {}
        volumeMounts:
        - mountPath: /drive
          name: guacd-claim0
        - mountPath: /record
          name: guacd-claim1
      hostname: guacd
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: guacd-claim0
        persistentVolumeClaim:
          claimName: guacd-claim0
      - name: guacd-claim1
        persistentVolumeClaim:
          claimName: guacd-claim1
status: {}
