apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\bin\kompose.exe convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\bin\kompose.exe convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: guacadb
        - name: MYSQL_PASSWORD
        - name: MYSQL_USER
          value: guacamole_user
        image: mysql/mysql-server
        imagePullPolicy: ""
        name: mysql
        resources: {}
      hostname: mysql
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
