apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
icon: https://www.sentry.dev/_assets2/favicon.ico
type: application
version: 11.5.1
appVersion: 21.7.0
dependencies:
  - name: redis
    repository: https://kibble1.github.io/charts/
    version: 9.3.2
    condition: redis.enabled
  - name: kafka
    repository: https://kibble1.github.io/charts/
    version: 12.0.0
    condition: kafka.enabled
  - name: clickhouse
    repository: https://kibble1.github.io/charts/
    version: 3.0.0
    condition: clickhouse.enabled
  - name: rabbitmq
    repository: https://kibble1.github.io/charts/
    version: 8.9.1
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: https://kibble1.github.io/charts/
    version: 10.2.4
    condition: postgresql.enabled
  - name: nginx
    repository: https://kibble1.github.io/charts/
    version: 9.3.3
    condition: nginx.enabled
