name: cachet
version: 0.0.2
appVersion: 2.5.0
description: The open source status page system.
home: http://cachethq.io/
icon: http://cachethq.io/img/logo.svg
keywords:
- status
- monitoring
- incident
- reporting
maintainers:
- name: alexei smirnov
  email: alexei@gotrg.com
sources:
- https://github.com/CachetHQ/Cachet
apiVersion: v1
deprecated: false
