# Default values for cachet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


cachetKey: "base64:CQ2el72ACEaD3NNX0xAnnWFMYmyAmr0lnQjJPeIB6rs="

postgresql:
  postgresDatabase: cachet

replicaCount: 1

image:
  repository: cachethq/docker
  tag: 2.3.18
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - localhost
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
