# Default values for cachet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cachethq/docker
  tag: "2.3.18"
  pullPolicy: Always

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  host: chart-example.local
  tls: []
  path: /
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# creates cachet database via posgres-controller
database:
  create: true
  host: cachet-db
  port: 5432
  name: cachet
  username: cachet
  instance_id: shared
  driver: pssql

env:
  public:
    # Application environments
    APP_DEBUG: false
    APP_LOG: errorlog
    DB_DRIVER: pgsql
    DOCKER: true
    CACHE_DRIVER: database
    SESSION_DRIVER: database
    QUEUE_DRIVER: database
    CACHET_EMOJI: false
    CACHET_BEACON: false
    # Email find them here  https://docs.cachethq.io/docs/configuring-mail
    MAIL_DRIVER: smtp
    MAIL_HOST: null
    MAIL_ADDRESS: null
    MAIL_PORT: 25
    MAIL_NAME: null
    MAIL_ENCRYPTION: tls

  # Update all with your own values
  private:
    APP_KEY: ""
    DB_PASSWORD: ""
    MAIL_USERNAME: null
    MAIL_PASSWORD: null

test:
  enabled: true

extraLabels: {}
