annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.6.0
dependencies:
- condition: zookeeper.enabled
  name: zookeeper
  repository: https://kibble1.github.io/charts/
  version: 6.x.x
description: Apache Kafka is a distributed streaming platform.
home: https://github.com/bitnami/charts/tree/master/bitnami/kafka
icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-110x117.png
keywords:
- kafka
- zookeeper
- streaming
- producer
- consumer
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: kafka
sources:
- https://kibble1.github.io/charts/
version: 12.0.0
