---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-daemon
  labels: {{- include "guacamole.labels.daemon" . | nindent 4 }}
spec:
  selector: {{- include "guacamole.selectorLabels.daemon" . | nindent 4 }}
  ports:
    - name: guacd
      port: 4822
      targetPort: guacd
