{{- if .Values.startupScripts }}
{{- $highAvailability := gt (int .Values.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-startup
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.startupScripts }}
  {{ $key }}: |

  {{- if .Values.pki.enabled }}
    /core-service=management/security-realm=ssl-realm:add()
    /core-service=management/security-realm=UndertowRealm:add()
    /core-service=management/security-realm=UndertowRealm/server-identity=ssl:add(alias={{ .Values.pki.keystore.alias }},keystore-path=keystore.jks, keystore-relative-to=jboss.server.config.dir, keystore-password=${env.PKI_KEYSTORE_PASS})
    /subsystem=undertow/server=default-server/https-listener=https:write-attribute(name=security-realm,value=ssl-realm)
    /subsystem=undertow/server=default-server/https-listener=https:write-attribute(name=verify-client,value=REQUESTED)
    /core-service=management/security-realm=ssl-realm/server-identity=ssl:add(alias={{ .Values.pki.keystore.alias }},keystore-relative-to=jboss.server.config.dir,keystore-password=${env.PKI_KEYSTORE_PASS},keystore-path=keystore.jks)
    /core-service=management/security-realm=ssl-realm/authentication=truststore:add(keystore-path=truststore.jks,keystore-relative-to=jboss.server.config.dir,keystore-password=${env.PKI_TRUSTSTORE_PASS})
  {{ end }}
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}
